const tablerIcons = require('@tabler/icons-react/dist/cjs/tabler-icons-react.cjs');

module.exports = {
	IconArrowRight: tablerIcons.IconArrowRight,
	IconBolt: tablerIcons.IconBolt,
	IconCalendar: tablerIcons.IconCalendar,
	IconChartBar: tablerIcons.IconChartBar,
	IconChartLine: tablerIcons.IconChartLine,
	IconCheck: tablerIcons.IconCheck,
	IconDownload: tablerIcons.IconDownload,
	IconEdit: tablerIcons.IconEdit,
	IconEye: tablerIcons.IconEye,
	IconEyeOff: tablerIcons.IconEyeOff,
	IconFastForward: tablerIcons.IconFastForward,
	IconFileMusic: tablerIcons.IconFileMusic,
	IconFileText: tablerIcons.IconFileText,
	IconFlame: tablerIcons.IconFlame,
	IconHeadphones: tablerIcons.IconHeadphones,
	IconHome: tablerIcons.IconHome,
	IconKeyboard: tablerIcons.IconKeyboard,
	IconLayoutDashboard: tablerIcons.IconLayoutDashboard,
	IconLanguage: tablerIcons.IconLanguage,
	IconLock: tablerIcons.IconLock,
	IconLogout: tablerIcons.IconLogout,
	IconMail: tablerIcons.IconMail,
	IconMedal: tablerIcons.IconMedal,
	IconMenu2: tablerIcons.IconMenu2,
	IconPencil: tablerIcons.IconPencil,
	IconPlayerPause: tablerIcons.IconPlayerPause,
	IconPlayerPlay: tablerIcons.IconPlayerPlay,
	IconPlayerSkipBack: tablerIcons.IconPlayerSkipBack,
	IconPlayerSkipForward: tablerIcons.IconPlayerSkipForward,
	IconRefresh: tablerIcons.IconRefresh,
	IconRewind: tablerIcons.IconRewind,
	IconSearch: tablerIcons.IconSearch,
	IconSettings: tablerIcons.IconSettings,
	IconShield: tablerIcons.IconShield,
	IconTarget: tablerIcons.IconTarget,
	IconTrophy: tablerIcons.IconTrophy,
	IconTrash: tablerIcons.IconTrash,
	IconUpload: tablerIcons.IconUpload,
	IconUser: tablerIcons.IconUser,
	IconUsers: tablerIcons.IconUsers,
	IconX: tablerIcons.IconX,
};